env:
  browser: true
  es6: true
  jest: true

extends:
  - airbnb
  - 'plugin:prettier/recommended'

rules:
  'import/no-extraneous-dependencies':
    - error
    - {
        devDependencies:
          [
            '**/*.test.js',
            '**/*.test.jsx',
            '**/*.spec.js',
            '**/*.spec.jsx',
            'config/**',
            './webpack.config.js',
          ],
      }
  'import/extensions':
    - error
    - ignorePackages
