env:
  browser: true
  es2021: true
  jest: true

extends:
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - standard
  - plugin:prettier/recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules:
  'import/no-extraneous-dependencies':
    - error
    - {
        devDependencies:
          [
            '**/*.test.{js,jsx,ts,tsx}',
            '**/*.spec.{js,jsx,ts,tsx}',
            'config/**',
            './webpack.config.js',
          ],
      }
  'import/extensions':
    - error
    - ignorePackages
