env:
  browser: true
  es2021: true
  jest: true

extends:
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - standard-with-typescript
  - plugin:prettier/recommended

parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - react
rules:
  'import/no-extraneous-dependencies':
    - error
    - devDependencies:
        - '**/*.test.{js,jsx,ts,tsx}'
        - '**/*.spec.{js,jsx,ts,tsx}'
        - 'config/**'
        - './webpack.config.js'

  'import/extensions':
    - error
    - ignorePackages
    - js: 'never'
      jsx: 'never'
      ts: 'never'
      tsx: 'never'

settings:
  'import/resolver':
    node:
      extensions: ['.js', '.jsx', '.ts', '.tsx']

overrides:
  - files: ['*.js', '*.jsx']
    rules:
      '@typescript-eslint/explicit-function-return-type': 0
      '@typescript-eslint/strict-boolean-expressions': 0
